import type { Config } from './world';

/** Starting tuning numbers. Change these, not the rules, after playtesting. */
export const defaultConfig: Config = {
  arenaRadius: 1500,
  throttleRate: 1 / 1.5,
  rimCurrentStart: 0.8,
  pointOfNoReturn: 0.95,
  fallSeconds: 1,
  sinkingSeconds: 1.5,
  waveCountdownSeconds: 5,
  waveSizeBase: 2,
  shipsFromWave: 4,
  enemyHealthGrowth: 0.05,
  spawnInner: 0.4,
  spawnOuter: 0.75,
  minSpawnDistance: 500,
  arrowRange: 245,
  arrowSpeed: 400,
  volleySeconds: 1,
  volleySpread: 0.1,
  cannonRange: 350,
  cannonSpeed: 250,
  cannonDamage: 10,
  cannonReloadSeconds: 3,
  cannonSpread: 0.1,
  fireballDamage: 20,
  fireballSplashRadius: 80,
  fireballBurn: { damagePerSecond: 2, burnSeconds: 3 },
  fireballRange: 450,
  fireballSpeed: 300,
  fireballCooldownSeconds: 6,
  fireballTurnRate: Math.PI / 2,
  fireballBurnOutSeconds: 2,
  wizardVesselsFromWave: 3,
  wizardVesselChance: 0.05,
  wizardFireballDamage: 20,
  wizardFireballCooldownSeconds: 10,
  wizardVesselGoldMultiplier: 3,
  regenRate: 0.01,
  regenDelaySeconds: 3,
  enemyCircleRange: 0.9,
  enemyTurnBack: 0.75,
  enemyCruiseThrottle: 0.6,
  // Two small dinghies meeting head-on at full speed close at 300 px/s.
  rammingDamage: 10,
  rammingSpeed: 300,
  vesselClasses: {
    // The sprite is 16 x 26 px, drawn at 2x.
    smallDinghy: { topSpeed: 150, acceleration: 100, turnRate: Math.PI / 2, radius: 20, health: 100, volleySize: 1, arrowDamage: 5, cannons: 0, highestCannons: 0, gold: 0 },
    // The enemy ship's model with white sails, bought in the Cabin. It gets going at 80% of the dinghy's rate.
    smallShip: { topSpeed: 180, acceleration: 80, turnRate: Math.PI / 2, radius: 40, health: 160, volleySize: 1, arrowDamage: 5, cannons: 1, highestCannons: 2, gold: 0 },
    // The same boat as the player's, but weaker.
    enemyDinghy: { topSpeed: 150, acceleration: 100, turnRate: Math.PI / 2, radius: 20, health: 30, volleySize: 1, arrowDamage: 5, cannons: 0, highestCannons: 0, gold: 5 },
    // The sprite is 66 x 113 px, drawn at 1x. Faster than a dinghy, but slow to get going.
    enemyShip: { topSpeed: 200, acceleration: 50, turnRate: Math.PI / 2, radius: 40, health: 120, volleySize: 3, arrowDamage: 5, cannons: 1, highestCannons: 1, gold: 20 },
  },
  cabin: {
    repair: { prices: [10], healShare: 0.25 },
    maxHealth: { prices: [30, 60, 120], healthShare: 0.25 },
    regen: { prices: [25, 50, 100], regenRate: 0.01 },
    arrowRate: { prices: [20, 40, 80], volleySeconds: [0.8, 0.65, 0.5] },
    volleySize: { prices: [30, 60, 120, 240], arrows: 1 },
    flamingArrows: { prices: [80], damagePerSecond: 2, burnSeconds: 3 },
    fireballDamage: { prices: [30, 60, 120], damage: [27, 35, 45] },
    fireballCooldown: { prices: [30, 60, 120], cooldownSeconds: [5, 4, 3] },
    moreCannons: { prices: [60, 120, 240] },
    smallShip: { prices: [150] },
  },
};
