import type { Config } from './world';

/** Starting tuning numbers. Change these, not the rules, after playtesting. */
export const defaultConfig: Config = {
  arenaRadius: 1500,
  throttleRate: 1 / 1.5,
  rimCurrentStart: 0.8,
  pointOfNoReturn: 0.95,
  fallSeconds: 1,
  sinkingSeconds: 1.5,
  waveCountdownSeconds: 5,
  waveSizeBase: 2,
  shipsFromWave: 4,
  enemyHealthGrowth: 0.05,
  spawnInner: 0.4,
  spawnOuter: 0.75,
  minSpawnDistance: 500,
  arrowRange: 350,
  arrowSpeed: 400,
  volleySeconds: 1,
  volleySpread: 0.1,
  fireballDamage: 40,
  fireballRange: 600,
  fireballSpeed: 300,
  fireballCooldownSeconds: 6,
  fireballTurnRate: Math.PI / 2,
  fireballBurnOutSeconds: 3,
  wizardVesselsFromWave: 3,
  wizardVesselChance: 0.05,
  wizardFireballDamage: 25,
  wizardFireballCooldownSeconds: 10,
  wizardVesselGoldMultiplier: 3,
  regenRate: 0.01,
  regenDelaySeconds: 3,
  enemyCircleRange: 0.9,
  enemyTurnBack: 0.75,
  enemyCruiseThrottle: 0.6,
  // Two small dinghies meeting head-on at full speed close at 300 px/s.
  rammingDamage: 10,
  rammingSpeed: 300,
  vesselClasses: {
    // The sprite is 16 x 26 px, drawn at 2x.
    smallDinghy: { topSpeed: 150, acceleration: 100, turnRate: Math.PI / 2, radius: 20, health: 100, volleySize: 1, arrowDamage: 5, gold: 0 },
    // The same boat as the player's, but weaker.
    enemyDinghy: { topSpeed: 150, acceleration: 100, turnRate: Math.PI / 2, radius: 20, health: 30, volleySize: 1, arrowDamage: 5, gold: 5 },
    // The sprite is 66 x 113 px, drawn at 1x. Faster than a dinghy, but slow to turn and to get going.
    enemyShip: { topSpeed: 200, acceleration: 50, turnRate: Math.PI / 4, radius: 40, health: 120, volleySize: 3, arrowDamage: 5, gold: 20 },
  },
  cabin: {
    repair: { prices: [10], healShare: 0.25 },
    maxHealth: { prices: [30, 60, 120], healthShare: 0.25 },
    regen: { prices: [25, 50, 100], regenRate: 0.01 },
    arrowRate: { prices: [20, 40, 80], volleySeconds: [0.8, 0.65, 0.5] },
    volleySize: { prices: [30, 60, 120, 240], arrows: 1 },
    fireballDamage: { prices: [30, 60, 120], damage: [55, 70, 90] },
    fireballCooldown: { prices: [30, 60, 120], cooldownSeconds: [5, 4, 3] },
    farthest: { prices: [25] },
    lowestHealth: { prices: [25] },
    highestHealth: { prices: [25] },
  },
};
